server:
  port: 9001
  servlet:
    context-path: /with-maven

spring:
  profiles:
    active: @profiles.active@

# admin properties
sys:
  admin:
    id: ${admin.id}
    name: @admin.name@
    age: @admin.age@
    address: @admin.address@